Turner.Web.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Turner.Web.UI.Controllers
{
    public class HomeController : Controller
    {
 
        /// <summary>
        /// Home Page
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }


        /// <summary>
        /// Contact Page
        /// </summary>
        /// <returns></returns>
        public ActionResult Contact()
        {
            return View();
        }

    }
}

Turner.Web.UI/Controllers/TitleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Turner.BusinessLogic;
using Turner.Model;

namespace Turner.Web.UI.Controllers
{
    public class TitleController : Controller
    {
 
        /// <summary>
        /// Search Title by name
        /// </summary>
        /// <param name="name"></param>
        /// <returns></returns>
        public ActionResult Index(string name)
        {
            TitleBC titleBC = new TitleBC();
            List<Title> model = titleBC.GetByName(name);
            return View(model);
        }

        /// <summary>
        /// Get title details by id
        /// </summary>
        /// <param name="titleId"></param>
        /// <returns></returns>
        public ViewResult Detail(int titleId)
        {
            TitleBC titleBC = new TitleBC();
            Title model = titleBC.GetById(titleId);
            return View(model);
        }

    }
}

Turner.Web.UI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact Us";
}

<h2>Contact Us</h2>

Sundarram Rajaram
sundarram.r.v@gmail.com

Turner.Web.UI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>History of film</h2>

<p>
The history of film began in the 1890s, with the invention of the first motion-picture cameras and the establishment of the first film production companies and cinemas. The films of the 1890s were under a minute long and until 1927, motion pictures were produced without sound. The first eleven years of motion pictures show the cinema moving from a novelty to an established large-scale entertainment industry. The films became several minutes long consisting of several shots. The first rotating camera for taking panning shots was built in 1897. The first film studios were built in 1897. Special effects were introduced and film continuity, involving action moving from one sequence into another, began to be used. In 1900, continuity of action across successive shots was achieved and the close-up shot was introduced. Most films of this period were what came to be called "chase films". The first use of animation in movies was in 1899. The first feature length multi-reel film was a 1906 Australian production. The first successful permanent theatre showing only films was "The Nickelodeon" in Pittsburgh in 1905. By about 1910, actors began to receive screen credit for their roles, and the way to the creation of film stars was opened. Regular newsreels were exhibited from 1910 and soon became a popular way for finding out the news. Overall, from about 1910, American films had the largest share of the market in all European countries except France.
</p>
<p>
New film techniques that were introduced in this period include the use of artificial lighting, fire effects and Low-key lighting (i.e. lighting in which most of the frame is dark) for enhanced atmosphere during sinister scenes. As films grew longer, specialist writers were employed to simplify more complex stories derived from novels or plays into a form that could be contained on one reel. Genres began to be used as categories; the main division was into comedy and drama, but these categories were further subdivided. The years of the First World War were a complex transitional period for the film industry. The exhibition of films changed from short one-reel programmes to feature films. Exhibition venues became larger and began charging higher prices. By 1914, continuity cinema was the established mode of commercial cinema. One of the advanced continuity techniques involved an accurate and smooth transition from one shot to another.
</p>
<p>
D. W. Griffith had the highest standing amongst American directors in the industry, because of the dramatic excitement he conveyed to the audience through his films. The American industry, or "Hollywood", as it was becoming known after its new geographical center in California, gained the position it has held, more or less, ever since: film factory for the world and exporting its product to most countries on earth. By the 1920s, the United States reached what is still its era of greatest-ever output, producing an average of 800 feature films annually,[1] or 82% of the global total (Eyman, 1997). During late 1927, Warners released The Jazz Singer, the first synchronized dialogue (and singing) in a feature film. By the end of 1929, Hollywood was almost all-talkie, with several competing sound systems (soon to be standardized). Sound saved the Hollywood studio system in the face of the Great Depression (Parkinson, 1995). Thus began what is now often called "The Golden Age of Hollywood", which refers roughly to the period beginning with the introduction of sound until the late 1940s. The American cinema reached its peak of efficiently manufactured glamour and global appeal during this period. The top actors of the era are now thought of as the classic film stars, such as Clark Gable, Katharine Hepburn, Humphrey Bogart, Greta Garbo, and the greatest box office draw of the 1930s, child performer Shirley Temple.
</p>

Turner.Web.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
   <div id="outer" class="outerPanel">
       <div class="page">
<header id="masthead" class="site-header" role="banner">
	
	<div class="logo">
		<h1 class="site-title"><a href="/" title="Ajaxify" rel="home">Cinema</a></h1>
	</div>
    <div class="searchPanel">
    @using (Html.BeginForm("Index", "Title"))
    {
       @Html.TextBox("name",null,new { @class= " searchtxt ",@placeholder="Search …"})
       <input type="submit" value="" class="searchbtn" />
    }
    </div>

    <div class="menuPanel"><a href="/Home/Contact" class="ajax">Contact Us</a></div>
	</header>
           <div id="content" class="site-main">
     @RenderBody()
               </div>
             </div>
   </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("http://balupton.github.io/history.js/scripts/bundled/html4+html5/jquery.history.js")
    @Scripts.Render("~/bundles/ajaxify")
    @RenderSection("scripts", required: false)
    <script>
        $(document).ready(function () {
            $('.searchbtn').ajaxify();
        });
    </script>
</body>

</html>

Turner.Web.UI/Views/Title/Detail.cshtml
@using Turner.Model
@model Title

@{
    ViewBag.Title = "Title Detail";
}

<h2>Detail</h2>

<h3>@Model.TitleName</h3>
@foreach (StoryLine storyLine in @Model.StoryLines)
{
    <p>
    @storyLine.Description</p>
}

Turner.Web.UI/Views/Title/Index.cshtml
@using Turner.Model
@model List<Title>

@{
    ViewBag.Title = "Search Result";
}

<h2>Search Result</h2>

@if(@Model != null && @Model.Count > 0)
{
<ul>
@foreach (Title title in @Model)
{
    <li>
        <a href="/Title/Detail?titleId=@title.TitleId">@title.TitleName - @title.ReleaseYear</a></li>
}
    </ul>
}
else
{ 
   <span>No result found</span>
}